SELECT *
FROM EMPLOYEE empl
WHERE empl.CHIEF_ID IS NULL

GO

SELECT *
FROM   EMPLOYEE employees, EMPLOYEE chiefs
WHERE  (employees.CHIEF_ID = chiefs.ID AND employees.SALARY > chiefs.SALARY)

GO

SELECT * 
FROM EMPLOYEE AS employees
WHERE employees.SALARY = 
	(SELECT MAX(SALARY) FROM EMPLOYEE AS empl 
		WHERE empl.DEPARTAMENT_ID = employees.DEPARTAMENT_ID)
GO

SELECT DEPARTAMENT_ID
FROM EMPLOYEE
GROUP BY DEPARTAMENT_ID
HAVING COUNT(*) <= 3

GO

SELECT *
FROM EMPLOYEE AS EMPL
	LEFT JOIN EMPLOYEE EMP ON 
		EMP.ID = EMPL.CHIEF_ID AND EMP.DEPARTAMENT_ID = EMPL.DEPARTAMENT_ID
WHERE EMP.ID IS NULL

GO

WITH SUMSALARY AS
   (SELECT DEPARTAMENT_ID, SUM(SALARY) SALARY
    FROM   EMPLOYEE
    GROUP  BY DEPARTAMENT_ID)
SELECT DEPARTAMENT_ID
FROM SUMSALARY
WHERE SALARY = (SELECT MAX(SALARY) FROM SUMSALARY)

